name: 'Stale Branches'
description: 'Finds and deletes stale branches'
author: 'Zero Cho'
inputs:
  repo-token:
    description: 'The token to be used to auth with GitHubs API. Can be passed in using `{{ secrets.GITHUB_TOKEN }}`'
    required: false
    default: ${{ github.token }}
  days-before-stale:
    description: 'Number of days a branch has been inactive before it is considered stale. Default: 120.'
    required: false
    default: '120'
  days-before-delete:
    description: 'Number of days a branch has been inactive before it is deleted. Default: 180.'
    required: false
    default: '180'
  compare-branches:
    description: 'Compares current branch with default branch. Options: off | info | save'
    required: false
    default: 'off'
  branches-filter-regex:
    description: 'An optional Regex that will be used to filter branches from this action.'
    required: false
    default: ''
outputs:
  deleted-branches:
    description: 'List of all deleted branches.'
  stale-branches:
    description: 'List of all stale branches.'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'delete'
  color: 'blue'
